# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 11:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_auto_20170421_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='ip_addr',
            field=models.CharField(default=b'0.0.0.0', max_length=20, verbose_name='IP Address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='port',
            field=models.IntegerField(default=0, max_length=5, verbose_name='Port'),
            preserve_default=False,
        ),
    ]
